### ISSUE TITLE
lmao enjoy

### ISSUE THREAD

**Issue by x0XP** [Elementars/Xulu-v1.5.2#12]
The client has been a private-paid client since its private re-release in 2018 and is still being updated today - if you bothered to add and talk to me on Discord I could've linked you to our private repo.

Thanks for being so ignorant and not doing the appropriate research though.

Will be submitting a DMCA takedown request now and this will not be up for debate. Enjoy.

**Comment by Elementars** [comment]
I could not find any evidence of a continuation of your project online. Hard to do research if you barely even mention how I managed to infringe on your outdated code despite me supposedly basing the entire client off of it, which is wildly incorrect and doesn't make any sense. The only reason you even targeted this to begin with is because I brought back the name from a client you had beef with in the past, even though I have no affiliation with that developer. If you had not gotten your panties in a twist and just tried to contact me and showed me your issues, this would have been resolved quickly. You chose the toxic path and you got what you should have expected. Good you dropped the YouTube argument, as you knew that was a stretch to begin with.

Take care.
