### ISSUE TITLE
wtf are you talking about lol

### ISSUE THREAD

**Issue by x0XP** [Elementars/Xulu-v1.5.2#13]
Uhm I didn't drop anything dude but okay keep copy & pasting dude I've submitted my DMCA takedown of this repo and all videos using your cp client

just because i didnt repeat myself doesn't mean im backtracking im just not wasting my time

Take care adios

p.s i am going to keep commenting issues that you're a copy&paster if you keep replying and closing my flagged issues with this repo

**Comment by Elementars** [comment]
Trying to strike down content that isn't yours is not going to work which is why I assumed you backtracked. You can still have fun trying, however. 

https://github.com/LeafHacker/xdolf

I checked the only thing you specifically mentioned, which is the module system, which is clearly different if you check each module class. It's quite a basic class and yet is still clearly unique.

Please elaborate on any issues if you want to continue them. Otherwise, it is not an issue and should be closed
